FROM centos:7

# build with:
#   docker build . -f Dockerfile_centos -t zongzw/f5-ps-21vvpn-centos:latest

# run with:
#   docker run -e USERNAME=$user -e PASSWORD=$pass --privileged zongzw/f5-ps-21vvpn-centos:latest


RUN yum update -y 

COPY ps-pulse-linux-9.1r2.0-b69-centos-rhel-64-bit-installer.rpm /root
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN yum install -y glib-networking webkitgtk3 libgnome-keyring libproxy-gnome libproxy-mozjs libproxy
RUN yum install -y sudo sysvinit-tools vim net-tools
RUN rpm -ivh /root/ps-pulse-linux-9.1r2.0-b69-centos-rhel-64-bit-installer.rpm

ENTRYPOINT /usr/local/pulse/PulseClient_x86_64.sh -h ${HOST:-183.84.2.165} -u ${USERNAME} -p ${PASSWORD} -r Users -L 5 > /dev/null 
