# System-wide .bashrc file for interactive bash(1) shells.
if [ -z "$PS1" ]; then
   return
fi

#PS1='\h:\W \u\$ '
#PS1="\e[0;31m[\u@\h \W]\$ \e[m"
#PS1="\e[0;31m[\u@\h \W]\e[m \$ "

color=$(($RANDOM % 6 + 1))
COLOR="\[$(tput setaf $color)\]"
RESET="\[$(tput sgr0)\]"
export PS1="${COLOR}[\u@\h \W]\$ ${RESET}"

# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"
