---

- hosts: hosts
  remote_user: root
  gather_facts: false
  tasks:
    - name: copy to remote
      copy: src={{ docker_image_tar }} dest=/root/docker-image.tar force=yes mode=0755
    - name: load docker image
      shell: docker load -i /root/docker-image.tar